// <auto-generated />
using System;
using CashMachine.Data.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CashMachine.Migrations
{
    [DbContext(typeof(CardDbContext))]
    [Migration("20191014174807_GenerateOwners")]
    partial class GenerateOwners
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CashMachine.Models.DataBase.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Money");

                    b.Property<Guid>("OwnerId");

                    b.Property<int>("Pin");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("CashMachine.Models.DataBase.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsAbleToTransfer");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Owner");

                    b.HasData(
                        new { Id = new Guid("3686f45d-5e74-4666-ae76-6cf898d36f90"), IsAbleToTransfer = true, LastName = "Kowalski", Name = "Piotr" },
                        new { Id = new Guid("98d50544-b91e-4491-9bf9-a4d601e5f873"), IsAbleToTransfer = true, LastName = "Nowak", Name = "Maciej" },
                        new { Id = new Guid("9710bb72-956f-4aca-ad4e-9fa133e385d4"), IsAbleToTransfer = true, LastName = "Janicki", Name = "Wojciech" },
                        new { Id = new Guid("8f18e657-4611-4ce1-9854-279fa327144c"), IsAbleToTransfer = true, LastName = "Olejniczak", Name = "Adam" }
                    );
                });

            modelBuilder.Entity("CashMachine.Models.DataBase.Card", b =>
                {
                    b.HasOne("CashMachine.Models.DataBase.Owner", "Owner")
                        .WithMany("Cards")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
